export function isAutogenerated(str: string): boolean {
  return str.indexOf('!') === 0;
}

export function isVerified(str: string): boolean {
  return !isAutogenerated(str);
}

export function stripMetacharacters(str: string): string {
  return isAutogenerated(str) ? str.slice(1) : str;
}
