---
admin:
  email: noLFIuTuNuHtGNC5s7oXGg==.jZFW/R4Z6NPVAAYZlkxuVq52+iJVXKuYtA==
  comment: Service account (Interslavic OSS)
big_l:
  email: tauFEHnFzAPUh/51I0H1vg==.xuHJMjRaDQSjuJLEQ/eH/dXY
  comment: Alla S.
k_rabkin:
  email: j+1MBEW9Bk68YpZmhC7d6Q==./7YoPQsMMWcOgvmT4aEvWXU=
  comment: Flavorization (RU)
lyer:
  email: KIg8UNKxo+CTWTROmPWX0A==.m29TYQbVSVr0m2K/tz9Fs58NmcN2
  comment: Flavorization (RU)
m_perelygina:
  email: od+5UY18MlR0UU5JgZXeCg==.59KsLkbiQk4crfv9IeJUakClBYY7/coq
  comment: Flavorization (RU)
michal_swat:
  email: 5p/HwdMFYKQ20Q+Fxq8WVQ==.E0+Cr+ZQOaTJS+gL+4i4Akt5KLWJ
  comment: Michal Swat
noomorph:
  email: POtzJBeWILeEUWI+y6uiyg==.1ZKER/vOxwRmWktigGkl7WYB
  comment: Jaroslav

