export const MISSING_OR_INVALID_TOKEN = 'MISSING_OR_INVALID_TOKEN';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
